version: "3"
services: 
    web:
        image: docker_first_mongo
        build: .
        command: "node server.js"
        ports: 
            - "4000:4000"
        depends_on: 
            - "mongo"
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
